ALTER TABLE game
    ADD COLUMN phase VARCHAR(20) NOT NULL DEFAULT 'LOBBY';

ALTER TABLE game
    ADD CONSTRAINT ck_game_phase
    CHECK (phase IN ('LOBBY', 'PREPARATION', 'QUESTION', 'ANSWERS_CLOSED', 'VOTE', 'JURY', 'RESULT'));
